// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'switch-container': string;
  'switch-container--theme-dark': string;
  'switch-container--theme-light': string;
  'switch-container__toggle': string;
  'switch-container__toggle--checked': string;
  'switch-container__toggle--theme-dark': string;
  'switch-container__toggle--theme-light': string;
}
export const cssExports: CssExports;
export default cssExports;
