// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'time': string;
  'timeBlock': string;
  'timeBlock--theme-dark': string;
  'timeBlock--theme-light': string;
  'timeBlock__separator': string;
  'timeBlock__separatorDot': string;
  'timeBlock__separatorDot--theme-dark': string;
  'timeBlock__separatorDot--theme-light': string;
}
export const cssExports: CssExports;
export default cssExports;
