// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'time': string;
  'timeBlock': string;
  'timeBlock__separator': string;
  'timeBlock__separatorDot': string;
}
export const cssExports: CssExports;
export default cssExports;
