// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__logo': string;
  'header__title': string;
}
export const cssExports: CssExports;
export default cssExports;
