// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footer__socialLink': string;
  'footer__socialLinkIcon': string;
  'footer__text': string;
}
export const cssExports: CssExports;
export default cssExports;
