// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'input--read-only': string;
  'input--theme-dark': string;
  'input--theme-light': string;
}
export const cssExports: CssExports;
export default cssExports;
