// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'taskBlock': string;
  'taskBlock--theme-dark': string;
  'taskBlock--theme-light': string;
  'taskBlockActive': string;
  'taskBlockActive--theme-dark': string;
  'taskBlockActive--theme-light': string;
  'taskBlock__actionTaskButton': string;
  'taskBlock__actionTaskButtonIcon': string;
  'taskBlock__actionTaskButtonIcon--theme-dark': string;
  'taskBlock__actionTaskButtonIcon--theme-light': string;
  'taskBlock__input': string;
  'taskBlock__listStyleIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
