// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divider': string;
  'tasksList': string;
  'tasksList__clearButton': string;
  'tasksList__clearButtonIcon': string;
  'tasksList__list': string;
  'tasksList__listBlock': string;
  'tasksList__listItem': string;
  'tasksList__listItemActive': string;
  'tasksList__listTitle': string;
  'tasksList__reminderElement': string;
  'tasksList__titleBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
