// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'divider': string;
  'divider--theme-dark': string;
  'divider--theme-light': string;
  'tasksList': string;
  'tasksList__clearButton': string;
  'tasksList__clearButton--theme-dark': string;
  'tasksList__clearButton--theme-light': string;
  'tasksList__clearButtonIcon': string;
  'tasksList__clearButtonIcon--theme-dark': string;
  'tasksList__clearButtonIcon--theme-light': string;
  'tasksList__list': string;
  'tasksList__listBlock': string;
  'tasksList__listItem': string;
  'tasksList__listItem--theme-dark': string;
  'tasksList__listItem--theme-light': string;
  'tasksList__listItemActive': string;
  'tasksList__listItemActive--theme-dark': string;
  'tasksList__listItemActive--theme-light': string;
  'tasksList__listTitle': string;
  'tasksList__listTitle--theme-dark': string;
  'tasksList__listTitle--theme-light': string;
  'tasksList__reminderElement': string;
  'tasksList__reminderElement--theme-dark': string;
  'tasksList__reminderElement--theme-light': string;
  'tasksList__titleBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
